---
- name: Create IDS mirror bridge (prerequisite)
  import_playbook: create_mirror_bridge.yml

- name: Destroy VyOS Packer
  import_playbook: destroy_vyos_packer.yml

- name: Provision VyOS image packer
  import_playbook: provision_vyos_packer.yml

- name: Pack VyOS image
  import_playbook: pack_vyos.yml

- name: Provision Router
  import_playbook: provision_router.yml

- name: Apply configuration
  import_playbook: configure_router.yml

- name: Configure OTEL monitoring
  import_playbook: configure_otel.yml

- name: Destroy VyOS Packer
  import_playbook: destroy_vyos_packer.yml
