- hosts: ai-tool-stack
  gather_facts: true
  roles:
    - common
    - dnf
    - linger
    - monitoring_agent

- name: Deploy LiteLLM
  import_playbook: litellm/site.yml

- name: Deploy OpenWebUI
  import_playbook: openwebui.yml
