---
- name: Provision step-ca LXC
  hosts: oracle
  gather_facts: true
  roles:
    - common
  tasks:
    - name: Pull fedora template
      community.general.proxmox_template:
        node: "{{ vm.step_ca.node }}"
        api_host: "{{ secrets.proxmox.cluster_host }}"
        api_user: "{{ secrets.proxmox.cluster_username }}"
        api_password: "{{ secrets.proxmox.cluster_password }}"
        url: "http://download.proxmox.com/images/system/fedora-41-default_20241118_amd64.tar.xz"

    - name: Check if step-ca LXC exists
      community.general.proxmox_vm_info:
        vmid: "{{ vm.step_ca.id }}"
        api_host: "{{ secrets.proxmox.cluster_host }}"
        api_user: "{{ secrets.proxmox.cluster_username }}"
        api_password: "{{ secrets.proxmox.cluster_password }}"
      register: previous_vm_info
      ignore_errors: true

    - name: Stop step-ca LXC
      community.general.proxmox:
        vmid: "{{ vm.step_ca.id }}"
        api_host: "{{ secrets.proxmox.cluster_host }}"
        api_user: "{{ secrets.proxmox.cluster_username }}"
        api_password: "{{ secrets.proxmox.cluster_password }}"
        state: stopped
      when: (previous_vm_info.proxmox_vms | length) > 0
      register: stop_result
      until: not stop_result.failed
      retries: 5
      delay: 5
      ignore_errors: true

    - name: Delete step-ca LXC
      community.general.proxmox:
        vmid: "{{ vm.step_ca.id }}"
        api_host: "{{ secrets.proxmox.cluster_host }}"
        api_user: "{{ secrets.proxmox.cluster_username }}"
        api_password: "{{ secrets.proxmox.cluster_password }}"
        state: absent
      when: (previous_vm_info.proxmox_vms | length) > 0
      register: delete_result
      until: not delete_result.failed
      retries: 5
      delay: 5
      ignore_errors: true

    - name: Create step-ca LXC
      community.general.proxmox:
        node: "{{ vm.step_ca.node }}"
        api_host: "{{ secrets.proxmox.cluster_host }}"
        api_user: "{{ secrets.proxmox.cluster_username }}"
        api_password: "{{ secrets.proxmox.cluster_password }}"
        vmid: "{{ vm.step_ca.id }}"
        password: "{{ secrets.step_ca.lxc_password }}"
        hostname: "{{ vm.step_ca.name }}"
        ostemplate: "local:vztmpl/fedora-41-default_20241118_amd64.tar.xz"
        ostype: "fedora"
        cores: "{{ vm.step_ca.cores }}"
        memory: "{{ vm.step_ca.memory }}"
        disk: "local-lvm:{{ vm.step_ca.disk_gb }}"
        nameserver: "{{ vm.router.ip.gigahub }}"
        netif:
          net0: "name=eth0,bridge=vmbr0,gw={{ vm.step_ca.gateway }},ip={{ vm.step_ca.ip }}/24,tag=2"
        features:
          - nesting=1
        unprivileged: true

    - name: Start step-ca LXC
      community.general.proxmox:
        vmid: "{{ vm.step_ca.id }}"
        api_host: "{{ secrets.proxmox.cluster_host }}"
        api_user: "{{ secrets.proxmox.cluster_username }}"
        api_password: "{{ secrets.proxmox.cluster_password }}"
        state: started
        timeout: 300
      ignore_errors: true
