---
- name: Provision step-ca LXC
  import_playbook: provision_lxc.yml

- name: Bootstrap step-ca LXC
  import_playbook: bootstrap_lxc.yml

- name: Apply baseline to step-ca LXC
  hosts: step-ca
  gather_facts: true
  roles:
    - common
    - dnf
    - vm_baseline
    - role: vm_monitoring_agent
      vars:
        podman_metrics_enabled: false

- name: Deploy step-ca
  import_playbook: deploy_step_ca.yml

- name: Provision AWS Trust Anchor for IAM Roles Anywhere
  import_playbook: provision_aws_trust.yml
