---
- name: Bootstrap SeaweedFS LXC
  import_playbook: bootstrap_lxc.yml

- name: Apply baseline to SeaweedFS LXC
  hosts: seaweedfs
  gather_facts: true
  roles:
    - common
    - dnf
    - vm_baseline
    - role: vm_monitoring_agent
      vars:
        podman_metrics_enabled: false

- name: Configure SeaweedFS services
  import_playbook: configure_seaweedfs.yml
