---
- name: Configure public gateway stack
  hosts: public-gateway
  gather_facts: true
  roles:
    - common
#     - dnf

# - name: Deploy tailscale
#   import_playbook: tailscale/site.yml

# - name: Deploy CrowdSec
#   import_playbook: crowdsec/site.yml

- name: Deploy caddy
  import_playbook: caddy/site.yml
