- hosts: gpu-workstation
  gather_facts: true
  roles:
    - common
    - dnf
    - linger
    - monitoring_agent
  tasks:
    - name: Install git
      become: true
      dnf:
        name: git
        state: present

- name: Setup Nvidia Drivers and Devices
  import_playbook: nvidia.yml

- name: Deploy Ollama and LLMs
  import_playbook: ollama.yml

- name: Deploy ComfyUI
  import_playbook: comfyui.yml

- name: Deploy Docling
  import_playbook: docling.yml

- name: Deploy JupyterLab
  import_playbook: jupyter/site.yml
