---
- name: Configure ZFS
  import_playbook: configure_zfs.yml

- name: Provision LXC
  import_playbook: provision.yml

- name: Configure NFS
  import_playbook: configure_nfs.yml

- name: Configure Proxmox NFS
  import_playbook: configure_proxmox_nfs.yml
