vyos_packer:
  id: 1000
  name: "vyos-packer"
  node: "oracle"
  cores: 4
  memory: 4096
  disk_gb: 10
  ip: "192.168.2.230"
  gateway: "192.168.2.1"

router:
  id: 1001
  name: "vyos-router"
  node: "oracle"
  cores: 8
  memory: 4096
  disk_gb: 128
  ip:
    gigahub: "192.168.2.231"
    vyos: "10.0.0.1"
  gateway:
    gigahub: "192.168.2.1"
    vyos: "10.0.0.0"

gateway_stack:
  id: 1002
  name: "gateway-stack"
  node: "oracle"
  cores: 8
  memory: 4096
  disk_gb: 128
  ip: "10.0.3.3"
  gateway: "10.0.3.1"
  ports:
    caddy: 80
    caddy_https: 443
    unifi_admin: 8443
    adguard_admin: 4000

monitoring_stack:
  id: 1003
  name: "monitoring-stack"
  node: "niobe"
  cores: 4
  memory: 4096
  disk_gb: 128
  ip: "10.0.3.5"
  gateway: "10.0.3.1"
  ports:
    otel_grpc: 4317
    otel_http: 4318
    grafana: 3000
    loki: 3100
    otel_metrics: 8888
    otel_prometheus: 8889
    prometheus: 9090

nfs:
  id: 1004
  name: "network-file-server"
  node: "smith"
  cores: 2
  memory: 1024
  disk_gb: 10
  gateway:
    gigahub: "192.168.2.1"
    vyos: "10.0.3.1"
  ip:
    gigahub: "192.168.2.232"
    vyos: "10.0.3.4"

dokploy:
  id: 1005
  name: "dokploy"
  node: "trinity"
  cores: 8
  memory: 16384
  disk_gb: 256
  ip: "10.0.3.6"
  gateway: "10.0.3.1"
  ports:
    dokploy: 3000
    traefik: 8080

gitlab:
  id: 1006
  name: "gitlab"
  node: "trinity"
  cores: 8
  memory: 8192
  disk_gb: 128
  ip: "10.0.3.7"
  gateway: "10.0.3.1"

backup_stack:
  id: 1007
  name: "backup-stack"
  node: "smith"
  cores: 4
  memory: 16384
  disk_gb: 20
  ip: "192.168.2.233"
  gateway: "192.168.2.1"
