---
- name: Setup monitoring agents
  hosts:
    - coupe
    - dev-workstation
    - dokploy
    - game-server
    - gateway-stack
    - gitlab
    - iot-management-stack
  roles:
    - monitoring_agent
