---
- name: Setup VM monitoring agents
  hosts:
    - dev-workstation
    - coupe
    - dokploy
    - game-server
    - gateway-stack
    - gitlab
    - iot-management-stack
    - lute
    - messaging-stack
    - gpu-workstation
    - ai-tool-stack
    - ups-management-stack
    - home-gateway-stack
    - monitoring-stack
    - router
    - nfs
    - backup-stack
    - cockpit
  roles:
    - vm_monitoring_agent
