---
- name: Update authorized keys
  hosts: all
  roles:
    - common
  tasks:
    - name: Print ansible_user
      debug:
        var: ansible_user

    - name: Update authorized keys
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ item }}"
        state: present
      loop: "{{ ssh_authorized_keys }}"
