---
- name: Upgrade Fedora VMs
  hosts:
    - cockpit
    - ups-management-stack
    - dev-workstation
    - gpu-workstation
    - messaging-stack
    - gitlab
    - ai-tool-stack
    - iot-management-stack
    - dokploy
    - home-gateway-stack
    - monitoring-stack
  gather_facts: true
  roles:
    - dnf

