---
- name: Provision OpenBao LXC
  hosts: oracle
  gather_facts: true
  roles:
    - common
  tasks:
    - name: Pull fedora template
      community.general.proxmox_template:
        node: "{{ vm.openbao.node }}"
        api_host: "{{ secrets.proxmox.cluster_host }}"
        api_user: "{{ secrets.proxmox.cluster_username }}"
        api_password: "{{ secrets.proxmox.cluster_password }}"
        url: "http://download.proxmox.com/images/system/fedora-41-default_20241118_amd64.tar.xz"

    - name: Check if OpenBao LXC exists
      community.general.proxmox_vm_info:
        vmid: "{{ vm.openbao.id }}"
        api_host: "{{ secrets.proxmox.cluster_host }}"
        api_user: "{{ secrets.proxmox.cluster_username }}"
        api_password: "{{ secrets.proxmox.cluster_password }}"
      register: previous_vm_info
      ignore_errors: true

    - name: Stop OpenBao LXC
      community.general.proxmox:
        vmid: "{{ vm.openbao.id }}"
        api_host: "{{ secrets.proxmox.cluster_host }}"
        api_user: "{{ secrets.proxmox.cluster_username }}"
        api_password: "{{ secrets.proxmox.cluster_password }}"
        state: stopped
      when: (previous_vm_info.proxmox_vms | length) > 0
      register: stop_result
      until: not stop_result.failed
      retries: 5
      delay: 5
      ignore_errors: true

    - name: Delete OpenBao LXC
      community.general.proxmox:
        vmid: "{{ vm.openbao.id }}"
        api_host: "{{ secrets.proxmox.cluster_host }}"
        api_user: "{{ secrets.proxmox.cluster_username }}"
        api_password: "{{ secrets.proxmox.cluster_password }}"
        state: absent
      when: (previous_vm_info.proxmox_vms | length) > 0
      register: delete_result
      until: not delete_result.failed
      retries: 5
      delay: 5
      ignore_errors: true

    - name: Create OpenBao LXC
      community.general.proxmox:
        node: "{{ vm.openbao.node }}"
        api_host: "{{ secrets.proxmox.cluster_host }}"
        api_user: "{{ secrets.proxmox.cluster_username }}"
        api_password: "{{ secrets.proxmox.cluster_password }}"
        vmid: "{{ vm.openbao.id }}"
        password: "{{ secrets.openbao.lxc_password }}"
        hostname: "{{ vm.openbao.name }}"
        ostemplate: "local:vztmpl/fedora-41-default_20241118_amd64.tar.xz"
        ostype: "fedora"
        cores: "{{ vm.openbao.cores }}"
        memory: "{{ vm.openbao.memory }}"
        disk: "local-lvm:{{ vm.openbao.disk_gb }}"
        nameserver: "{{ vm.home_gateway_stack.ip }}"
        netif:
          net0: "name=eth0,bridge=vmbr0,gw={{ vm.openbao.gateway }},ip={{ vm.openbao.ip }}/24,tag=2"
        features:
          - nesting=1
        unprivileged: true

    - name: Start OpenBao LXC
      community.general.proxmox:
        vmid: "{{ vm.openbao.id }}"
        api_host: "{{ secrets.proxmox.cluster_host }}"
        api_user: "{{ secrets.proxmox.cluster_username }}"
        api_password: "{{ secrets.proxmox.cluster_password }}"
        state: started
        timeout: 300
      ignore_errors: true
