---
- name: Configure GitLab CI/CD Integration
  import_playbook: gitlab_integration.yml

- name: Deploy Dokku Platform
  import_playbook: dokku.yml

- name: Deploy Infisical
  import_playbook: infisical.yml

- name: Deploy Temporal
  import_playbook: temporal.yml
