---
- name: restart otel collector
  systemd:
    name: aether-otel-collector
    state: restarted
    daemon_reload: yes
  become: true

- name: restart nvidia gpu exporter
  systemd:
    name: aether-nvidia-gpu-exporter
    state: restarted
    daemon_reload: yes
  become: true
