collections:
  - name: community.general
    version: 10.3.0
  - name: community.sops
    version: 2.0.0
  - name: vyos.vyos
    version: 6.0.0
  - name: containers.podman
    version: 1.16.2
  - name: prometheus.prometheus
    version: 0.27.4
