---
- name: Bootstrap Smallweb LXC
  import_playbook: bootstrap_lxc.yml

- name: Apply baseline to Smallweb LXC
  hosts: smallweb
  gather_facts: true
  roles:
    - common
    - dnf
    - role: vm_baseline
      vars:
        ssh_ca_user_principals:
          smallweb:
            - ci-deploy
            - admin
    - role: vm_monitoring_agent
      vars:
        podman_metrics_enabled: false

- name: Configure Smallweb
  import_playbook: configure_smallweb.yml
