---
- name: Configure ZFS Snapshots
  hosts: smith
  roles:
    - common
  tasks:
    - name: Install sanoid
      apt:
        name: sanoid
        state: present

    - name: Ensure sanoid configuration directory exists
      file:
        path: /etc/sanoid/
        state: directory
        mode: "0755"

    - name: Write sanoid config
      template:
        src: sanoid.conf.j2
        dest: "/etc/sanoid/sanoid.conf"
        owner: root
        group: root
        mode: "0644"
      notify: Restart sanoid timer

    - name: Ensure sanoid snapshot timer is enabled and started
      systemd:
        name: sanoid.timer
        state: started
        enabled: true
        daemon_reload: true

  handlers:
    - name: Restart sanoid timer
      listen: Restart sanoid timer
      systemd:
        name: sanoid.timer
        state: restarted
        daemon_reload: true
