---
- hosts: backup-stack
  gather_facts: true
  roles:
    - common
    - vm_baseline
    - vm_monitoring_agent

- name: Configure Proxmox Backup Server
  import_playbook: configure_pbs.yml

- name: Configure Proxmox backups
  import_playbook: configure_proxmox_backups.yml

- name: Configure Offsite backups
  import_playbook: configure_offsite_backups/site.yml
