---
- name: Configure Proxmox Backup Server
  import_playbook: configure_pbs.yml

- name: Configure Proxmox backups
  import_playbook: configure_proxmox_backups.yml

- name: Configure ZFS snapshots
  import_playbook: configure_zfs_snapshots.yml
